# Generated by Django 2.1.4 on 2018-12-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_pubished',
            new_name='is_published',
        ),
    ]
